[workspace]
resolver = "2"
members = [
    "aya-metrics",
    "aya-metrics-common",
    "aya-metrics-ebpf",
]

[workspace.package]
# Use a single version for all workspace members
version = "0.2.1"
edition = "2021"
homepage = "https://github.com/aya-metrics-rs/aya-metrics"
repository = "https://github.com/aya-metrics-rs/aya-metrics"
authors = ["OliverGavin"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
aya = { path = "../aya/aya", version = "~0.13" }
aya-obj = { path = "../aya/aya-obj" }
aya-log = { path = "../aya/aya-log" }
aya-log-common = { path = "../aya/aya-log-common" }
aya-ebpf = "0.1"

# Keep workspace dependencies here so it is easier to increment versions in a single place
aya-metrics-common = { version = "0.2", path = "./aya-metrics-common" }

