group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
# We are not on a 8 segment screen, it is not 1979
max_width = 120
array_width = 100
fn_call_width = 100
chain_width = 80
# Prevent carriage returns
newline_style = "Unix"
