[package]
name = "aya-metrics"
description = "A metrics library for eBPF programs."
keywords = ["bpf", "ebpf", "metrics", "telemetry"]

version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
aya = { workspace = true }
aya-metrics-common = { workspace = true, features=["user"] }
metrics = "0.24"
futures = "0.3.28"
thiserror = "1.0.38"
tokio = { version = "1.32", features = ["time"] }

[lib]
path = "src/lib.rs"

[dev-dependencies]
anyhow = "1.0.93"
serial_test = "0.10.0"
tokio = { version = "1.32", features = ["full", "test-util"] }
aya = { workspace = true, features = ["test-utils"] }
aya-obj = { workspace = true }
